version: 1.0.{build}
image: Visual Studio 2017
configuration: Release
platform: Any CPU

before_build:
- appveyor-retry dotnet restore "source\source.sln"

build_script:
- dotnet build "source\ICanHazDadJoke.NET" -c %CONFIGURATION%

after_build:
- dotnet pack "source\ICanHazDadJoke.NET" -c %CONFIGURATION% --no-build

test_script:
- dotnet test "source\ICanHazDadJoke.NET.Tests" -c %CONFIGURATION%

artifacts:
- path: source/ICanHazDadJoke.NET/bin/$(configuration)/netstandard1.1/ICanHazDadJoke.NET.dll
- path: source/ICanHazDadJoke.NET/bin/$(configuration)/ICanHazDadJoke.NET.*.nupkg
