trigger:
- master

variables:
  BUILD_NUMBER: $[counter('$(Build.SourceBranchName)_counter', 1)]
  PACKAGE_VERSION: '1.0.$(BUILD_NUMBER)'

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: DotNetCoreCLI@2
  displayName: 'Restore packages'
  inputs:
    command: 'restore'
    projects: './source/source.sln'
- task: DotNetCoreCLI@2
  displayName: 'Build library'
  inputs:
    command: 'build'
    projects: './source/ICanHazDadJoke.NET/ICanHazDadJoke.NET.csproj'
    arguments: '-c Release /p:Version=$(PACKAGE_VERSION)'
- task: DotNetCoreCLI@2
  displayName: 'Package NuGets'
  inputs:
    command: 'pack'
    packagesToPack: './source/ICanHazDadJoke.NET/ICanHazDadJoke.NET.csproj'
    nobuild: true
    versioningScheme: 'off'
    buildProperties: 'Configuration=Release /p:Version=$(PACKAGE_VERSION)'
- task: DotNetCoreCLI@2
  displayName: 'Run tests'
  inputs:
    command: 'test'
    projects: './source/ICanHazDadJoke.NET.Tests/ICanHazDadJoke.NET.Tests.csproj'
    arguments: '-c Release'
- task: PublishBuildArtifacts@1
  displayName: 'Publish artifacts'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
